version: '3.2'

services:

  explorer-api:
    build: .
    image: polkascan-explorer-api
    ports:
      - '8080:8000'
    volumes:
      - '.:/usr/src/app'
    command: ./start.sh
    environment:
      - PYTHONPATH=/usr/src/app
      - ENVIRONMENT=dev